### PR TITLE
Update to use python 3.10

### PR DESCRIPTION
**Pull request by TimSC**
Update to use python 3.10, recent torch libraries, plus minor fixes

### CODE REVIEW

**Comment by ZhenglinZhou** [comment]
Hi @TimSC, many thanks for your PR! 

But I am worried about the performance difference when changing the torch version. Do you mind evaluating this new version on WFLW?

If you have any questions, feel free to leave a comment or email me (zhouzhenglincs@gmail.com).

**Comment by TimSC** [comment]
Good point, I didn't evaluate the speed on either pytorch version. I might check my fixes work on python 3.8/pytorch 1.6 using anaconda as well. Do you have a way to properly evaluate the speed? Are we talking about training or testing speed or both?

**Comment by TimSC** [comment]
I tried various versions of torch and found the performance is consistent between 1.7 and 1.13. However, there is a performance drop moving to torch 2.0. This may be because torch 2 models require torch.compile to be fast but attempting model compilation hits a different error. As far as this PR is concerned, we may as well stick with torch 1.13.

[log-py3.7-torch1.7.0-batchsize8-oldeig.txt](https://github.com/ZhenglinZhou/STAR/files/12705221/log-py3.7-torch1.7.0-batchsize8-oldeig.txt)
[log-py3.7-torch1.9.0-batchsize8-neweig.txt](https://github.com/ZhenglinZhou/STAR/files/12705222/log-py3.7-torch1.9.0-batchsize8-neweig.txt)
[log-py3.7-torch1.9.0-batchsize8-oldeig.txt](https://github.com/ZhenglinZhou/STAR/files/12705223/log-py3.7-torch1.9.0-batchsize8-oldeig.txt)
[log-py3.7-torch1.13.0-batchsize8.txt](https://github.com/ZhenglinZhou/STAR/files/12705224/log-py3.7-torch1.13.0-batchsize8.txt)
[log-py3.10-torch1.13.1-batchsize8.txt](https://github.com/ZhenglinZhou/STAR/files/12705225/log-py3.10-torch1.13.1-batchsize8.txt)
[log-py3.10-torch2.0.1-batch8.txt](https://github.com/ZhenglinZhou/STAR/files/12705226/log-py3.10-torch2.0.1-batch8.txt)

**Comment by ZhenglinZhou** [comment]
Hi @TimSC, thank you very much! I believe this update may make STAR more convenient.

**Comment by ZhenglinZhou** [comment]
Hi, @TimSC. Thanks again! However, I noticed that you are not listed as a contributor for STAR. It's strange. I hope you can be a collaborator of this project. A collaborator invitation has been sent, please kindly accept it. :)

**Pull request merged**
